### ISSUE TITLE
about loading model.txt in opencv version code

### ISSUE THREAD

**Issue by lucaskyle** [computer-vision/takahashi2012cvpr#3]
loading 'xxxxxxxxxxxxxx/data/camera.txt' = [2445.724853515625, 0, 0;
 0, 0, 0;
 0, 0, 0]
i just run the source code,
then i found this,
is this right?

I also find camera.txt is so different from other inputs txt file.
the numbers are divided by '，',
should I delete them?

**Comment by lucaskyle** [comment]
loading 'XXXXXXXXXX/data/input1.txt' = [648.847351, 335.148407;
 606.541321, 329.269287;
 564.161194, 323.357544]


loading 'XXXXXXXXXX/data/input2.txt' = [1384.842407, 431.004852;
 1320.590454, 420.41626;
 1257.821167, 410.182312]


loading 'XXXXXXXXXX/data/input3.txt' = [1025.244629, 584.0162350000001;
 984.783997, 582.214844;
 945.333618, 580.599976]


loading 'XXXXXXXXXX/data/model.txt' = [0, 0, 0;
 27.5, 0, 0;
 55, 0, 0]


loading 'XXXXXXXXXX/data/camera_m.txt' = [2445.724853515625, 0, 819.2930297851562;
 0, 2442.3916015625, 660.1307373046875;
 0, 0, 1]

**Comment by lucaskyle** [comment]
am i right?

**Comment by nbhr** [comment]
Thank you for the message.  This is a mandatory file to provide the camera intrinsic parameter, and should be as follows (https://github.com/computer-vision/takahashi2012cvpr/blob/master/data/camera.txt).

```
2445.7248535156250000, 0.0000000000000000, 819.2930297851562500
0.0000000000000000, 2442.3916015625000000, 660.1307373046875000
0.0000000000000000, 0.0000000000000000, 1.0000000000000000
```

This may be because the file loader in OpenCV does not support the comma-separated format.  We have fixed the file in the repository.  Could you please check if this solves the issue?

**Comment by lucaskyle** [comment]
thx  
I fixed  the problem
